apiVersion: v1
kind: Service
metadata:
  name: go-app-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-source-ranges: "203.0.113.0/24,198.51.100.0/24"  
spec:
  type: LoadBalancer
  selector:
    app: go-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6969
